name: libsys
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  image_field: ^0.0.9

  flutter_gen: any
  isbn: ^1.0.4
  flash: ^3.1.0
  light_sensor: ^3.0.0
  simple_barcode_scanner: ^0.1.1
  nfc_manager: ^3.4.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
